from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from shopping_app.views import (
    home,
    add_to_cart,
    add_item_to_store,
    item_update,
    item_delete,
    item_list,
    view_store,
    register_user,
    view_item_detail,
    checkout,
    view_cart,
    leave_review,
    create_buyer_account,
    api_login,
    create_store,
    api_add_item,
    api_get_reviews,
    StoreListBySeller,
    ProductListInStore,
    view_store_detail,
    store_list,
    twitter_callback,
)

urlpatterns = [
    path('', home, name='home'),
    path("add-to-cart/<int:item_id>/", add_to_cart, name="add_to_cart"),
    path("cart/", view_cart, name="view_cart"),
    path("add-item/", add_item_to_store, name="add_item_to_store"),
    path("items/", item_list, name="item_list"),
    path("items/<int:item_id>/", view_item_detail, name="item_detail"),
    path('item/edit/<int:pk>/', item_update, name='item_update'),
    path("items/<int:pk>/delete/", item_delete, name="item_delete"),
    path("item/<int:item_id>/leave-review/", leave_review,
         name="leave_review"),
    path("store/<int:pk>/", view_store, name="view_store"),
    path("store/<int:store_id>/detail/", view_store_detail,
         name="view_store_detail"),
    path("register/", register_user, name="register_user"),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(next_page='home'), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path("checkout/", checkout, name="checkout"),
    path("create_buyer_account/", create_buyer_account,
         name="create_buyer_account"),
    path('stores/', store_list, name='store_list'),
    path('twitter/callback/', twitter_callback, name='twitter_callback'),

    # API Endpoints
    path("api/login/", api_login, name="api_login"),
    path("api/stores/", create_store, name="create_store"),
    path("api/add-item/", api_add_item, name="api_add_item"),
    path("api/reviews/", api_get_reviews, name="api_get_reviews"),
    path("api/reviews/store/<int:store_id>/", api_get_reviews,
         name="api_get_store_reviews"),
    path("api/reviews/item/<int:item_id>/", api_get_reviews,
         name="api_get_item_reviews"),
    path("api/store/<int:seller_id>/", StoreListBySeller.as_view(),
         name="store_list_by_seller"),
    path("api/store/<int:store_id>/items/", ProductListInStore.as_view(),
         name="product_list_in_store"),
]
