# Generated by Django 5.2 on 2025-05-02 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiego_news', '0004_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='indiego_news.publisher'),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
