# Generated by Django 5.2 on 2025-04-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_item_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_featured',
        ),
    ]
